AVAX_ID = "U8iRqJoiJm8xZHAacmvYyZVwqQx6uDNtQeP3CQ6fcgQk3JqnK"
AVAX_DENOMS = [1, 10, 100]
AVAX_NAME = "Avax"
AVAX = (AVAX_NAME, AVAX_ID, AVAX_DENOMS)

ETHER_ID = "2"
ETHER_DENOMS = [1, 5, 20]
ETHER_NAME = "Etherium"
ETHER = (ETHER_NAME, ETHER_ID, ETHER_DENOMS)

ASSET_TYPES = [AVAX, ETHER]
ASSET_NAMES, ASSET_IDS, ASSET_DENOMS = map(list, zip(*ASSET_TYPES))