
START_PROCESS, SELECT_OPTIONS, GET_JOIN_INFO, COLLECT_INPUTS, COLLECT_SIGS, ISSUE_TX = range(6) #different states for a CoinJoin
JOIN_AMOUNTS = [1, 10, 100]
MIN_USER_BOUND = 2
MAX_USER_BOUND = 20
DEFAULT_LOWER_USER_BOUND = 5
DEFAULT_UPPER_USER_BOUND = 8
AVAX = "U8iRqJoiJm8xZHAacmvYyZVwqQx6uDNtQeP3CQ6fcgQk3JqnK"
ETHER = "2"
ASSET_TYPES = [AVAX]
REQUEST_TERMINATOR = b'\r\n\r\n'
STANDARD_BURN_AMOUNT = 0.001